var target = document.getElementById('target');
var titles = [
		'My opinions belong to the void.'.link('javascript:window.location.reload(true)'),
		'All are equal.'.link('javascript:window.location.reload(true)'),
		'World Peace'.link('javascript:window.location.reload(true)'),
		'Spacing, Kerning, Typesetting.'.link('javascript:window.location.reload(true)'),
		'I enjoy doing things that demand patience and precision.'.link('javascript:window.location.reload(true)'),
		'It’s okay to be happy, even in your imperfections and failures because that’s what makes you human. And being human is messy and beautiful.'.link('javascript:window.location.reload(true)'),
		'I want you to know that happiness is okay, even when the world is aching. Because what the world desperately needs is positivity, and it starts with a smile.'.link('javascript:window.location.reload(true)'),
		'Deadline is the source of my inspiration.'.link('javascript:window.location.reload(true)'),
		'Opinions belong to my dogs.'.link('javascript:window.location.reload(true)'),
		'Imagining mermaids since 1984.'.link('javascript:window.location.reload(true)'),
		'Less is less, more is more. Not less not more is not more not less.'.link('javascript:window.location.reload(true)'),
		'Furniture designer turned Unicorn and I create my own typefaces.'.link('javascript:window.location.reload(true)'),
		'I am 6 years old.'.link('javascript:window.location.reload(true)'),
		'I need a coffee.'.link('javascript:window.location.reload(true)'),
		'Let’s get coffee?'.link('javascript:window.location.reload(true)'),
		'Coffee?'.link('javascript:window.location.reload(true)'),
		'I am.'.link('javascript:window.location.reload(true)'),
		'Lorem Ipsum.'.link('javascript:window.location.reload(true)'),
		'Aluminium'.link('javascript:window.location.reload(true)'),
		'If you don’t like graffiti, you’re not looking at the big picture'.link('javascript:window.location.reload(true)'),
		'We can do better.'.link('javascript:window.location.reload(true)'),
		'Profoundly'.link('javascript:window.location.reload(true)'),
		'Pure'.link('javascript:window.location.reload(true)'),
		'Pure passion.'.link('javascript:window.location.reload(true)'),
		'I love sushi.'.link('javascript:window.location.reload(true)'),
		'Party, Sleep, Repeat.'.link('javascript:window.location.reload(true)'),
		'Love is worth everything. Everything.'.link('javascript:window.location.reload(true)'),
		'The secret to creativity is knowing how to hide your sources.'.link('javascript:window.location.reload(true)'),
		'I want you to know that it is okay to suck at something.'.link('javascript:window.location.reload(true)'),
		'Time is irrelevant.'.link('javascript:window.location.reload(true)'),
		'Making the world a better place better than any one else.'.link('javascript:window.location.reload(true)'),
		'Turtle is my spirit animal.'.link('javascript:window.location.reload(true)'),
		'Enter the Void'.link('javascript:window.location.reload(true)'),
		'Lefty, Colorblind'.link('javascript:window.location.reload(true)'),
		'Don’t try to be original. Just try to be nice.'.link('javascript:window.location.reload(true)'),
		'Not minimalist. Purist.'.link('javascript:window.location.reload(true)'),
		'Simplicity'.link('javascript:window.location.reload(true)'),
		'Humanity'.link('javascript:window.location.reload(true)'),
		'Polymath'.link('javascript:window.location.reload(true)'),
		'Generate'.link('javascript:window.location.reload(true)'),
		'Charrette'.link('javascript:window.location.reload(true)'),
		'Reload'.link('javascript:window.location.reload(true)'),
		'INFP'.link('javascript:window.location.reload(true)'),
		'White space'.link('javascript:window.location.reload(true)'),
		'Composition'.link('javascript:window.location.reload(true)'),
		'Refresh'.link('javascript:window.location.reload(true)'),
		'Process'.link('javascript:window.location.reload(true)'),
		'Disrupt'.link('javascript:window.location.reload(true)'),
		'Ephemeral'.link('javascript:window.location.reload(true)'),
		'FTUX'.link('javascript:window.location.reload(true)'),
		'Insight'.link('javascript:window.location.reload(true)'),
		'Magic'.link('javascript:window.location.reload(true)'),
		'Dank'.link('javascript:window.location.reload(true)'),
		'Synergize'.link('javascript:window.location.reload(true)'),
		'Pizza'.link('javascript:window.location.reload(true)'),
		'Sushi'.link('javascript:window.location.reload(true)'),
		'Beer me.'.link('javascript:window.location.reload(true)'),
		'Kale'.link('javascript:window.location.reload(true)'),
		'Next'.link('javascript:window.location.reload(true)'),
		'Kombucha'.link('javascript:window.location.reload(true)'),
		'Sriracha'.link('javascript:window.location.reload(true)'),
		'Cooper Black'.link('javascript:window.location.reload(true)'),
		'Restart'.link('javascript:window.location.reload(true)'),
		'Continue'.link('javascript:window.location.reload(true)'),
		'New'.link('javascript:window.location.reload(true)'),
		'More'.link('javascript:window.location.reload(true)'),
		'Advance'.link('javascript:window.location.reload(true)'),
		'Optimize'.link('javascript:window.location.reload(true)'),
		'Random'.link('javascript:window.location.reload(true)'),
		'Randomize'.link('javascript:window.location.reload(true)'),
		'Randomization'.link('javascript:window.location.reload(true)'),
		'Peace'.link('javascript:window.location.reload(true)'),
		'Love'.link('javascript:window.location.reload(true)'),
		'Cool'.link('javascript:window.location.reload(true)'),
		'Rad'.link('javascript:window.location.reload(true)'),
		'Let’s chat 💬'.link('javascript:window.location.reload(true)'),
		'Okay, bye ☃️'.link('javascript:window.location.reload(true)'),
		'❌⭕️❌⭕️'.link('javascript:window.location.reload(true)'),
		'❤️'.link('javascript:window.location.reload(true)'),
		'💩'.link('javascript:window.location.reload(true)'),
		'🥑'.link('javascript:window.location.reload(true)'),
		'🌮'.link('javascript:window.location.reload(true)'),
		'🙏'.link('javascript:window.location.reload(true)'),
		'🍆'.link('javascript:window.location.reload(true)'),
		'🐢'.link('javascript:window.location.reload(true)'),
		'🌵'.link('javascript:window.location.reload(true)'),
		'🚀'.link('javascript:window.location.reload(true)'),
		'🐳'.link('javascript:window.location.reload(true)')
	];

function newTitle() {
    var i = (Math.random() * titles.length) | 0;
    target.innerText = titles[i];
}

newTitle();
