var target = document.getElementById('target');
var titles = [
    'Half feminist, half vegan.',
				'My opinions belong to the void.',
				'All are equal.',
				'World Peace',
				'Space, Kern, Type.',
				'I enjoy doing things that demand patience and precision.',
				'It’s okay to be happy, even in your imperfections and failures because that’s what makes you human. And being human is messy and beautiful.',
				'I want you to know that happiness is okay, even when the world is aching. Because what the world desperately needs is positivity, and it starts with a smile.',
				'Deadline is the source of my inspiration.',
				'Opinions belong to my dogs.',
				'Less is less, more is more. Not less not more is not more not less.',
				'Furniture designer turned Unicorn and I create my own typefaces.',
				'I am 6 years old.',
				'I need a coffee.',
				'Let’s get coffee?',
				'Coffee?',
				'I am.',
				'Lorem Ipsum.',
				'Aluminium',
				'If you don’t like graffiti, you’re not looking at the big picture',
				'We can do better.',
				'Profoundly.',
				'Pure',
				'Pure passion.',
				'I love sushi.',
				'Party, Sleep, Repeat.',
				'Love is worth everything. Everything.',
				'The secret to creativity is knowing how to hide your sources.',
				'I want you to know that it is okay to suck at something.',
				'Time is irrelevant.',
				'Making the world a better place better than any one else.',
				'My spirit animal is a turtle.',
				'Enter the Void',
				'Lefty and colorblind',
				'Don’t try to be original. Just try to be nice.',
				'Not minimalist. Purist.',
				'Simplicity',
				'Humanity',
				'Polymath',
				'Generate',
				'Charrette',
				'Reload',
				'INFP',
				'White space',
				'Composition',
				'Refresh',
				'Process',
				'Disrupt',
				'Ephemeral',
				'FTUX',
				'Insight',
				'Magic',
				'Dank',
				'Synergize',
				'Pizza',
				'Sushi',
				'Beer me.',
				'Kale',
				'Next',
				'Kombucha',
				'Sriracha',
				'Cooper Black',
				'Restart',
				'Continue',
				'More',
				'Text me.',
				'Advance',
				'Optimize',
				'Random',
				'Randomize',
				'Randomization',
				'Peace',
				'Love',
				'Cool',
				'Rad',
				'Let’s chat 💬',
				'Okay, bye ☃️',
				'❌⭕️❌⭕️',
				'💩',
				'☕️',
				'🍺🍺🍺',
				'👀',
				'🎈',
				'👾',
				'🥑',
				'🌈',
				'🌮',
				'🙏',
				'👻',
				'🍆',
				'🐢',
				'🌵',
				'🍕',
				'🚀',
				'🐳'
];

function newTitle() {
    var i = (Math.random() * titles.length) | 0;
    target.innerText = titles[i];
}

newTitle();
